artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: harishkumardatalab/medical-insurance-price-prediction
  local_file_path: artifacts/data_ingestion/Medical_insurance.csv
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Medical_insurance.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Medical_insurance.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/transformed_train.csv
  test_data_path: artifacts/data_transformation/transformed_test.csv
  model_name: model.joblib


